// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webApp.Data;

#nullable disable

namespace webApp.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("webApp.Models.Attribute", b =>
                {
                    b.Property<int>("AttributeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("datas")
                        .HasColumnType("TEXT");

                    b.Property<string>("titles")
                        .HasColumnType("TEXT");

                    b.HasKey("AttributeID");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("webApp.Models.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("website")
                        .HasColumnType("TEXT");

                    b.HasKey("BrandID");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("webApp.Models.Categori", b =>
                {
                    b.Property<int>("CategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriID");

                    b.ToTable("Categoris");
                });

            modelBuilder.Entity("webApp.Models.DisCountCode", b =>
                {
                    b.Property<int>("DisCountCodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("code")
                        .HasColumnType("TEXT");

                    b.Property<int?>("discount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("exp_date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("gen_date")
                        .HasColumnType("TEXT");

                    b.HasKey("DisCountCodeID");

                    b.ToTable("disCountCodes");
                });

            modelBuilder.Entity("webApp.Models.Object", b =>
                {
                    b.Property<int>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AttributeID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrandID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubCategoriID")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("discount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("image")
                        .HasColumnType("TEXT");

                    b.Property<double?>("price")
                        .HasColumnType("REAL");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.HasKey("ObjectID");

                    b.HasIndex("AttributeID")
                        .IsUnique();

                    b.HasIndex("BrandID");

                    b.HasIndex("SubCategoriID");

                    b.ToTable("Objects");
                });

            modelBuilder.Entity("webApp.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("discountCodeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("paymentCode")
                        .HasColumnType("TEXT");

                    b.Property<double?>("total_price")
                        .HasColumnType("REAL");

                    b.HasKey("PaymentID");

                    b.HasIndex("UserID");

                    b.HasIndex("discountCodeID")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("webApp.Models.Sell", b =>
                {
                    b.Property<int>("SellID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ObjectID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaymentID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("SellID");

                    b.HasIndex("ObjectID");

                    b.HasIndex("PaymentID");

                    b.HasIndex("UserID");

                    b.ToTable("Sells");
                });

            modelBuilder.Entity("webApp.Models.SubCategori", b =>
                {
                    b.Property<int>("SubCategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("image")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.HasKey("SubCategoriID");

                    b.HasIndex("CategoriID");

                    b.ToTable("SubCategoris");
                });

            modelBuilder.Entity("webApp.Models.Token", b =>
                {
                    b.Property<int>("TokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("exp_dateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("gen_dateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("token")
                        .HasColumnType("TEXT");

                    b.HasKey("TokenID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("webApp.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("first_name")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("webApp.Models.Object", b =>
                {
                    b.HasOne("webApp.Models.Attribute", "Attribute")
                        .WithOne("Object")
                        .HasForeignKey("webApp.Models.Object", "AttributeID");

                    b.HasOne("webApp.Models.Brand", "Brand")
                        .WithMany("Object")
                        .HasForeignKey("BrandID");

                    b.HasOne("webApp.Models.SubCategori", "SubCategori")
                        .WithMany("Objects")
                        .HasForeignKey("SubCategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Brand");

                    b.Navigation("SubCategori");
                });

            modelBuilder.Entity("webApp.Models.Payment", b =>
                {
                    b.HasOne("webApp.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserID");

                    b.HasOne("webApp.Models.DisCountCode", "DisCountCode")
                        .WithOne("Payment")
                        .HasForeignKey("webApp.Models.Payment", "discountCodeID");

                    b.Navigation("DisCountCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("webApp.Models.Sell", b =>
                {
                    b.HasOne("webApp.Models.Object", "Object")
                        .WithMany("Sells")
                        .HasForeignKey("ObjectID");

                    b.HasOne("webApp.Models.Payment", "Payment")
                        .WithMany("Sells")
                        .HasForeignKey("PaymentID");

                    b.HasOne("webApp.Models.User", "User")
                        .WithMany("Sells")
                        .HasForeignKey("UserID");

                    b.Navigation("Object");

                    b.Navigation("Payment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("webApp.Models.SubCategori", b =>
                {
                    b.HasOne("webApp.Models.Categori", "Categori")
                        .WithMany("subCategoris")
                        .HasForeignKey("CategoriID");

                    b.Navigation("Categori");
                });

            modelBuilder.Entity("webApp.Models.Token", b =>
                {
                    b.HasOne("webApp.Models.User", "User")
                        .WithOne("token")
                        .HasForeignKey("webApp.Models.Token", "UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("webApp.Models.Attribute", b =>
                {
                    b.Navigation("Object");
                });

            modelBuilder.Entity("webApp.Models.Brand", b =>
                {
                    b.Navigation("Object");
                });

            modelBuilder.Entity("webApp.Models.Categori", b =>
                {
                    b.Navigation("subCategoris");
                });

            modelBuilder.Entity("webApp.Models.DisCountCode", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("webApp.Models.Object", b =>
                {
                    b.Navigation("Sells");
                });

            modelBuilder.Entity("webApp.Models.Payment", b =>
                {
                    b.Navigation("Sells");
                });

            modelBuilder.Entity("webApp.Models.SubCategori", b =>
                {
                    b.Navigation("Objects");
                });

            modelBuilder.Entity("webApp.Models.User", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Sells");

                    b.Navigation("token");
                });
#pragma warning restore 612, 618
        }
    }
}
